'use client';

import React, { useRef, useCSS } from 'react';
import { css } from '@emotion/react';
import { Laugh } from 'lucide-react';
import { colors } from './styles';

const IconMat = () => {
  return (
    <>
    <div css={{
      width: 0,
      height: 0,
      borderRight: '150px solid transparent',
      borderTop: '460px solid white',
      marginTop: '0px',
      zIndex: 10,
      position: 'absolute',
      right: '342px'
    }}></div>
    <div css={{
      width: 0,
      height: 0,
      borderLeft: '150px solid transparent',
      borderBottom: '460px solid white',
      marginTop: '0px',
      zIndex: 10,
      position: 'absolute',
      right: '0px'
    }}></div>
      <div
        css={{
          width: '900px',
          flexGrow: 1,
        }}
      >
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
        <Laugh />
      </div>
    </>
    
  );
};
export default IconMat;
